# https://picodotdev.github.io/blog-bitix/2019/05/crear-de-forma-sencilla-y-rapida-maquinas-virtuales-de-virtualbox-con-vagrant/
# https://www.itwonderlab.com/es/cluster-kubernetes-vagrant-ansible/
# https://azure.microsoft.com/es-es/blog/automating-sap-deployments-in-microsoft-azure-using-terraform-and-ansible/
# https://tech.serhatteker.com/post/2020-11/add-ssh-public-key-to-vagrant/

IMAGE_NAME = "bento/almalinux-8"
MASTERS_NUM = 1
MASTERS_CPU = 2 
MASTERS_MEM = 1024
IP_BASE = "192.168.50."
VAGRANT_DISABLE_VBOXSYMLINKCREATE=1
Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    #config.ssh.private_key_path = "../id_rsa.pub"
    #config.ssh.username = "vagrant"
    (1..MASTERS_NUM).each do |i|      
        config.vm.define "terminal" do |master|
            master.vm.box = IMAGE_NAME
            master.vm.network "private_network", ip: "#{IP_BASE}#{i + 10}"
            master.vm.hostname = "terminal"
            master.vm.provider "virtualbox" do |v|
                v.memory = MASTERS_MEM
                v.cpus = MASTERS_CPU
            end            
            
        end
    end
end