apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: practica
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.192
    path: /srv/mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  namespace: practica
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.192
    path: /srv/wp