kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-mysql-pvc
  namespace: demo-wordpress
spec:
  storageClassName: storage-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 750Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-wp-pvc
  namespace: demo-wordpress
spec:
  storageClassName: storage-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1750Mi

